"""AeroTrace shared contracts (LOCKED — change only via CLAUDE.md §5)."""

from aerotrace.contracts.ids import hash_bytes, make_id
from aerotrace.contracts.models import (
    DEFAULT_BANNER,
    AnalysisMethod,
    Artifact,
    ArtifactKind,
    AskAnswer,
    BuildContext,
    Claim,
    ClaimStatus,
    Classification,
    ContextBundle,
    Edge,
    EdgeType,
    Evidence,
    FileCoverage,
    FileStatus,
    ImpactItem,
    ImpactResult,
    Node,
    NodeKind,
    NormalizedCodeModel,
    Origin,
    PathHop,
    Quality,
    ReviewAction,
    ReviewEvent,
    RunManifest,
    TraversalLimits,
    ValidationReport,
)
from aerotrace.contracts.repository import GraphRepository

from aerotrace.contracts.fakes import (  # isort: skip
    EMPTY_IMPACT_MESSAGE,
    FakeGraphRepository,
    fake_answer,
    fake_compute_impact,
    fake_generate_artifact,
    fake_run_analysis,
    load_sample_ncm,
)

__all__ = [
    "DEFAULT_BANNER",
    "EMPTY_IMPACT_MESSAGE",
    "AnalysisMethod",
    "Artifact",
    "ArtifactKind",
    "AskAnswer",
    "BuildContext",
    "Claim",
    "ClaimStatus",
    "Classification",
    "ContextBundle",
    "Edge",
    "EdgeType",
    "Evidence",
    "FakeGraphRepository",
    "FileCoverage",
    "FileStatus",
    "GraphRepository",
    "ImpactItem",
    "ImpactResult",
    "Node",
    "NodeKind",
    "NormalizedCodeModel",
    "Origin",
    "PathHop",
    "Quality",
    "ReviewAction",
    "ReviewEvent",
    "RunManifest",
    "TraversalLimits",
    "ValidationReport",
    "fake_answer",
    "fake_compute_impact",
    "fake_generate_artifact",
    "fake_run_analysis",
    "hash_bytes",
    "load_sample_ncm",
    "make_id",
]
